repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
    - id: fmt
    - id: cargo-check
    - id: clippy
# Current repo hooks
- repo: local
  hooks:
  - id: test
    name: test
    description: Test with cargo test.
    entry: cargo test
    language: system
    pass_filenames: false
    always_run: false
    fail_fast: true
